version: "3.8"

services:
  web-dev:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    container_name: web-dev
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
